# tomcat
server:
  port: 2001

# eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

# spring
spring:
  application:
    name: config-server

  # config
  cloud:
    config:
      server:
        git:
          uri: http://git.jiagouedu.com/java-vip/spring-cloud-mall-config.git

  # rabbitmq
  rabbitmq:
    host: 192.168.0.60
    port: 5672
    username: guest
    password: guest